### ISSUE TITLE
[Bug] Black Formatter GitHub Action 변경

### ISSUE THREAD

**Issue by kms7530** [kms7530/Salsa#26]
# 작업 내용
- 기존에 사용중인 Black formatter GitHub Action에서 `token` 값을 넣어줘도 오류가 발생하는 상태. 
- 해당 GitHub Action은 유지보수가 되지 않고, [공식 GitHub Action](https://github.com/psf/black/blob/main/action.yml) 사용을 권장중. 
- 다음의 issue가 모두 `main`에 병합된 이후 변경 예정. 
    - #11
    - #23 
    - #25

**Comment by kms7530** [comment]
작업이 끝나시면 아래 comment 부탁드립니다!
@elan1537 @Jeon-jisu

**Comment by jsujeon** [comment]
작업 끝났습니다 @kms7530

**Comment by kms7530** [comment]
끝나신 내용 PR 올려주세요. @Jeon-jisu

**Comment by kms7530** [comment]
권한 문제 해결.
